
services:
  ttp:
    build:
      context: .
      target: ttp_development
      args:
        - UID=${UID}
        - GID=${GID}
        - USERNAME=${USERNAME}
    container_name: ttp
    volumes:
      - .:/app
    devices:
      - /dev/dri:/dev/dri
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-modeset:/dev/nvidia-modeset
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools
    ports:
      - "5679:5679"  # Python debugger port for ttp
    stdin_open: true
    tty: true
    command: tail -f /dev/null
    working_dir: /app
    gpus: all
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    networks:
      - uttp_net

  ros:
    build:
      context: .
      target: ros_development
      args:
        - UID=${UID}
        - GID=${GID}
        - USERNAME=${USERNAME}
    container_name: ros
    volumes:
      - .:/app
    devices:
      - /dev/dri:/dev/dri
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-modeset:/dev/nvidia-modeset
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools
    ports:
      - "5680:5679"  # Python debugger port for ros
    stdin_open: true
    tty: true
    command: tail -f /dev/null
    working_dir: /app
    gpus: all
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    networks:
      - uttp_net

networks:
  uttp_net:
    driver: bridge
