name: research
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  # Core Python and frequently used libraries
  - python=3.11
  - numpy
  - scipy
  - matplotlib
  - networkx
  - pyyaml

  # PyTorch and GPU dependencies
  - pytorch
  - torchvision
  - torchaudio

  # Simulation and robotics libraries
  - gymnasium
  - opencv

  # Other utilities and libraries
  - h5py
  - trimesh
  - rtree
  - cryptography
  - progressbar
  - click

  # Developer tools
  - pip
  - pip:
      - black
      - isort
      - pyright
      - pytest
      - coverage
      # - GitPython~=3.1.40
      - transforms3d
      - addict
      # - ipython~=8.20.0
      - future
      - termcolor
      - pymeshlab
      - graphviz
      # - bddl~=3.5.0
      - nest_asyncio
      - imageio
      - imageio-ffmpeg
