<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>robotiq_gripper</name>
  <version>0.0.0</version>
  <description>TODO: Package description</description>
  <maintainer email="kimz1121@naver.com">lab6</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>
  
  <buildtool_depend>rosidl_default_generators</buildtool_depend>

  <build_depend>libmodbus-dev</build_depend>
  <build_depend>robotiq_gripper_interface</build_depend>
  <build_depend>sensor_msgs</build_depend>
  <build_depend>rclcpp</build_depend>
  <build_export_depend>libmodbus-dev</build_export_depend>
  <build_export_depend>robotiq_gripper_interface</build_export_depend>
  <build_export_depend>sensor_msgs</build_export_depend>
  <build_export_depend>rclcpp</build_export_depend>
  <exec_depend>libmodbus-dev</exec_depend>
  <exec_depend>robotiq_gripper_interface</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>rclcpp</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
