log_level: DEBUG
predefined: true
scene_type:
- kitchen
- bathroom
ros: false
simulation: true
start_idx: 1
approaches:
- src/baselines/cpm.py
- src/baselines/edf/dag_edf.py
- src/dag_bayesian.py
llm_scripts: null
scene_lists:
  kitchen:
  - FloorPlan1
  - FloorPlan7
  - FloorPlan13
  - FloorPlan18
  - FloorPlan27
  bathroom:
  - FloorPlan422
  - FloorPlan426
  - FloorPlan427
  real_world: null
num_runs_per_instruction: 1
max_retries: 10
retry_delay_seconds: 2
max_workers: 2
instruction_delay_seconds: 0
cloud_rendering: true
execute_dict:
  FloorPlan18:
  - 14
  - 17
  FloorPlan27:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  - 18
  - 19
  - 20
  FloorPlan422:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  - 18
  - 19
  - 20
  FloorPlan426:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  - 18
  - 19
  - 20
  FloorPlan427:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  - 18
  - 19
  - 20
