# Configuration for run_all.py

simulation: true # Enable Simulation mode
cloud_rendering: true
num_runs_per_instruction: 1 # Number of times to run each instruction
max_retries: 10 # Maximum number of retries for failing LLM scripts
retry_delay_seconds: 2 # Delay in seconds between retries
max_workers: 15 # Maximum number of workers
instruction_delay_seconds: 0 # Delay in seconds between instructions
# Logging configuration
log_level: "DEBUG" # Log level for the script. Options: 'DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL'

start_idx: 1 # Start index for the instruction


# Execution settings
# List of approaches (scripts) to run
approaches:
  - "src/baselines/cpm.py"
  - "src/baselines/edf/dag_edf.py"
  - "src/dag_bayesian.py"
# Scripts that use LLMs and are subject to retries on failure
llm_scripts:
  # - "src/baselines/progprompt/prog_ai2thor.py"
  # - "src/baselines/cap/cap_ai2thor.py"

# Scene lists for each scene type

scene_type: # Default scene type to run. Options: 'kitchen', 'bathroom'
  - kitchen
  # - bathroom 
  # - real_world
scene_lists:
  kitchen:
    # - "FloorPlan1"  
    # - "FloorPlan7"
    # - "FloorPlan13"
    # - "FloorPlan18"
    # - "FloorPlan27"

  bathroom:
    # - "FloorPlan419"
    # - "FloorPlan422"
    # - "FloorPlan426"
    # - "FloorPlan427"
  real_world:
    - "FloorPlan301"






ablation_configs:
  - NONE_URGENCY
  - NONE_REMAINING_WORK
  - NONE_MONITORING
  - GREEDY
  - DEFAULT

init_prior_configs:
  - OVER_ESTIMATE
  - UNDER_ESTIMATE
  - CORRECT_ESTIMATE  

# ------------------------------------------------------------------------------
# Task Filtering
# ------------------------------------------------------------------------------
task_folder_name: "sampled_10_instruction_set_for_final_experiment" # Folder under assets/tasks/
min_task_count: 0
min_constraint_count: 0




# ==============================================================================
# Ablation Study Configurations
# ==============================================================================
