# Configuration for run_all.py
# Logging configuration
log_level: "INFO" # Log level for the script. Options: 'DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL'

# Execution mode
predefined: true # Use predefined numbered instructions (1-20) instead of loading from JSON files
scene_type: "kitchen" # Default scene type to run. Options: 'kitchen', 'bathroom'
ros: false # Enable ROS communication
simulation: true # Enable Simulation mode
start_idx: 30 # Start index for the instruction
# Execution settings
# List of approaches (scripts) to run
approaches:
  - "src/baselines/cpm.py"
  # - "src/baselines/edf/dag_edf.py"
  # - "src/dag_bayesian.py"
  # - "src/baselines/progprompt/prog_ai2thor.py"
  # - "src/baselines/cap/cap_ai2thor.py"


# Scripts that use LLMs and are subject to retries on failure
llm_scripts:
  - "src/baselines/progprompt/prog_ai2thor.py"
  - "src/baselines/cap/cap_ai2thor.py"

# Scene lists for each scene type
scene_lists:
  kitchen:
    - "FloorPlan1"  
    - "FloorPlan7"
    - "FloorPlan13"
    - "FloorPlan18"
    - "FloorPlan27"
  bathroom:
    # - "FloorPlan419"
    # - "FloorPlan422"
    # - "FloorPlan426"
    # - "FloorPlan427"
  realworld:
    # - "FloorPlan301"

# Number of times to run each instruction
num_runs_per_instruction: 1

# Retry settings for LLM scripts
# Maximum number of retries for failing LLM scripts
max_retries: 10
# Delay in seconds between retries
retry_delay_seconds: 2 