int16 object_id_a
int16 object_id_b
int16 instruction
int16 sequence_id -1 #기본 값 -1 
string sub_action "move"
bool relativity false
# 기본 값인 경우 : 값이 이전값으로 부터 순차적으로 증가 (0 에서부터 시작) 
# 0 이상의 값을 지정하는 경우 : 특정 번호로 이동 가능
---
bool success
